### PR TITLE
refactor token gen to use jjwt 0.11.5

### PR DESCRIPTION
**Pull request by FDDTheLucario**

### CODE REVIEW

**Comment by wsingleton** [comment]
some tests are failing with 500s

**Comment by wsingleton** [comment]
that isnt the pom.xml, but the change does fix the broken tests :)

**Comment by FDDTheLucario** [comment]
> we should not merge this in until we know that the `application-deploy.yml` is updated. otherwise, the pipeline will break

yeah, i let devops know about this

**Comment by wsingleton** [comment]
@LemuelThomas, please review and approve this once you update the `application-deploy.yml` in the S3 bucket fetched during build

**Review by LemuelThomas — APPROVED** [review]

**Pull request merged**
